/** Extra search terms keyed by emoji slug from unicode-emoji-json. */
export const SLUG_ALIASES = {
  grinning_face: ["lol", "lmao", "haha", "happy", "smile"],
  beaming_face_with_smiling_eyes: ["grin", "happy"],
  face_with_tears_of_joy: ["joy", "rofl", "lmao", "lol", "crying"],
  rolling_on_the_floor_laughing: ["rofl", "lmao", "lol"],
  slightly_smiling_face: ["smile", "happy"],
  winking_face: ["wink"],
  smiling_face_with_heart_eyes: ["love", "heart", "crush"],
  face_blowing_a_kiss: ["kiss", "love"],
  kissing_face: ["kiss"],
  thinking_face: ["think", "hmm"],
  face_with_raised_eyebrow: ["suspicious", "skeptical"],
  neutral_face: ["meh"],
  expressionless_face: ["blank"],
  face_without_mouth: ["silent"],
  face_with_rolling_eyes: ["eyeroll"],
  smirking_face: ["smirk"],
  persevering_face: ["struggle"],
  disappointed_face: ["sad"],
  crying_face: ["sad", "tear"],
  loudly_crying_face: ["sob", "sad"],
  weary_face: ["tired"],
  tired_face: ["tired", "exhausted"],
  pleading_face: ["puppy", "please"],
  red_heart: ["love", "heart"],
  broken_heart: ["heartbreak", "sad"],
  fire: ["lit", "hot"],
  hundred_points: ["100", "perfect", "score"],
  thumbs_up: ["+1", "yes", "ok", "good", "like", "approve"],
  thumbs_down: ["-1", "no", "bad", "dislike"],
  clapping_hands: ["clap", "applause"],
  raising_hands: ["celebrate", "hooray"],
  folded_hands: ["pray", "please", "thanks"],
  eyes: ["look", "watch"],
  eye: ["look"],
  sparkles: ["shine", "magic"],
  party_popper: ["party", "celebrate"],
  birthday_cake: ["birthday", "bday"],
  pizza: ["food"],
  hamburger: ["burger", "food"],
  hot_dog: ["food"],
  taco: ["food"],
  beer_mug: ["beer", "drink"],
  clinking_beer_mugs: ["cheers", "beer"],
  wine_glass: ["wine", "drink"],
  coffee: ["cafe", "morning"],
  dog: ["puppy", "pet"],
  cat: ["kitty", "pet"],
  unicorn: ["fantasy"],
  rainbow: ["pride"],
  sun: ["sunny", "weather"],
  cloud: ["weather"],
  umbrella: ["rain", "weather"],
  snowflake: ["snow", "cold", "winter"],
  soccer_ball: ["football", "futbol"],
  american_football: ["nfl"],
  basketball: ["nba", "ball"],
  trophy: ["win", "winner"],
  rocket: ["launch", "space"],
  airplane: ["flight", "travel"],
  automobile: ["car"],
  house: ["home"],
  office: ["work"],
  briefcase: ["work", "job"],
  laptop: ["computer", "work"],
  mobile_phone: ["phone", "cell"],
  envelope: ["email", "mail"],
  check_mark: ["done", "yes", "ok"],
  cross_mark: ["no", "wrong", "x"],
  warning: ["alert", "caution"],
  information: ["info"],
  question_mark: ["question", "help"],
  exclamation_mark: ["important"],
  pile_of_poo: ["poop", "shit"],
  ghost: ["spooky", "halloween"],
  jack_o_lantern: ["halloween", "pumpkin"],
  christmas_tree: ["xmas", "holiday"],
  wrapped_gift: ["gift", "present"],
  money_bag: ["money", "rich"],
  money_with_wings: ["expensive"],
  chart_increasing: ["stocks", "growth"],
  chart_decreasing: ["stocks", "down"],
};

/** Whole-query hints that boost specific slugs (ISO codes, phrases). */
export const QUERY_TO_SLUGS = {
  us: ["flag_united_states"],
  usa: ["flag_united_states"],
  america: ["flag_united_states"],
  uk: ["flag_united_kingdom"],
  gb: ["flag_united_kingdom"],
  fr: ["flag_france"],
  de: ["flag_germany"],
  jp: ["flag_japan"],
  cn: ["flag_china"],
  ca: ["flag_canada"],
  au: ["flag_australia"],
  br: ["flag_brazil"],
  mx: ["flag_mexico"],
  in: ["flag_india"],
  es: ["flag_spain"],
  it: ["flag_italy"],
  "thumbs up": ["thumbs_up"],
  "thumbs down": ["thumbs_down"],
  "+1": ["thumbs_up"],
  "-1": ["thumbs_down"],
  poop: ["pile_of_poo"],
  shit: ["pile_of_poo"],
  heart: ["red_heart", "orange_heart", "yellow_heart", "green_heart", "blue_heart", "purple_heart"],
  smile: ["grinning_face", "slightly_smiling_face"],
  sad: ["crying_face", "disappointed_face"],
  laugh: ["face_with_tears_of_joy", "grinning_face"],
  ok: ["ok_hand", "thumbs_up"],
  wave: ["waving_hand"],
  pray: ["folded_hands"],
  clap: ["clapping_hands"],
  eyes: ["eyes"],
  skull: ["skull"],
  ghost: ["ghost"],
  alien: ["alien"],
  robot: ["robot"],
  poop: ["pile_of_poo"],
};

/** @type {Record<string, string[]>} */
export const SLUG_ALIASES_EXTRA = {
  face_with_tears_of_joy: ["tysm", "funny", "xd"],
  skull: ["dead", "ded"],
  see_no_evil_monkey: ["monkey"],
  hear_no_evil_monkey: ["monkey"],
  speak_no_evil_monkey: ["monkey"],
  hot_pepper: ["spicy"],
  banana: ["banana"],
  avocado: ["avocado"],
  egg: ["egg"],
  cookie: ["cookie"],
  chocolate_bar: ["chocolate"],
  candy: ["candy"],
  star_struck: ["star", "wow"],
  exploding_head: ["mind", "blown"],
  shushing_face: ["shh", "quiet"],
  face_with_monocle: ["monocle"],
  nerd_face: ["nerd"],
  zany_face: ["crazy"],
  money_mouth_face: ["money"],
  cowboy_hat_face: ["cowboy"],
  disguised_face: ["disguise"],
  smiling_imp: ["devil", "imp"],
  imp: ["devil"],
  jack_o_lantern: ["halloween"],
  christmas_tree: ["xmas"],
  snowman: ["winter"],
  comet: ["comet"],
  shooting_star: ["wish"],
  tada: ["party", "confetti"],
  balloon: ["party"],
  gift: ["present"],
  bell: ["bell"],
  megaphone: ["announce"],
  mute: ["muted"],
  speaker_low_volume: ["volume"],
  battery: ["battery"],
  electric_plug: ["plug"],
  light_bulb: ["idea"],
  wrench: ["tool"],
  hammer: ["tool"],
  link: ["url"],
  check_mark_button: ["done"],
  cross_mark_button: ["close"],
  name_badge: ["badge"],
  musical_note: ["music"],
  microphone: ["mic"],
  movie_camera: ["film"],
  camera: ["photo"],
  video_game: ["gaming", "game"],
  joystick: ["game"],
  chess_pawn: ["chess"],
  puzzle_piece: ["puzzle"],
  teddy_bear: ["bear"],
  pi_ata: ["party"],
  nesting_dolls: ["dolls"],
  pinata: ["party"],
};

Object.assign(SLUG_ALIASES, SLUG_ALIASES_EXTRA);
